### ISSUE TITLE
Не ставит комментарий на своей же странице

### ISSUE THREAD

**Issue by zzhhkkvv** [aeonixlegit/vk-autocomment#1]
Если в Link вставить свою страницу, поставить любое сообщение и тебе напишешь не ты, а например твой друг новый пост, то коммент не поставится.
Не пишет ошибок, а просто видимо такой функции нет, а жаль, на ком ещё тестить-то?(

**Comment by raywave** [comment]
Привет, извини за долгий ответ.

Всё потому, что скрипт работает на получении новостей вместо парсинга стен сообществ, это убирает лимит на 5000 запросов на стену в день, а так-же уменьшает количество запросов.

Можешь попробовать сделать новую группу и тестировать на ней.

Со следующим обновлением обновлю докментацию, спасибо.

Не стесняйся открывать вопрос, если есть новая информация.
