### ISSUE TITLE
Немогу понять что не так...

### ISSUE THREAD

**Issue by nawmem** [aeonixlegit/vk-autocomment#2]
Ошибка: Доступ запрещён (возможно, в группе от имени которой отправляется комментарий у аккаунта нет роли редактора) [15] 
Я являюсь создателем группы

{
  "token": "54846",
  "group_link": "vk.com/***world",
  "ignore_links": true,
  "links": [
  ],
  "messages": [
    "Всем привет, эту группу видели? vk.com/***world"
  ],
  "attachments": [
  ],
  "autosubscribe": true,
  "like": true,
  "comment": true,
  "likecomment": true,
  "time": 10000
}

**Comment by raywave** [comment]
Привет, извини за долгий ответ. Нужно конкретно тестировать, в чем проблема.

Можешь отписать мне в телеграм: @aeonixlegit, будем разбираться.

**Comment by raywave** [comment]
Долго не было ответа, закрываю тему.
