### ISSUE TITLE
комментирование встреч

### ISSUE THREAD

**Issue by LEONushka08** [aeonixlegit/vk-autocomment#3]
Здравствуйте, я хотел поставить автокомментирование в мероприятии вк, но программа не распознала это как сообщество и выдаёт ошибку. Вопрос, можно это как-то настроить или нет?

**Comment by raywave** [comment]
Привет, извини за долгий ответ. Сейчас посмотрю.

**Comment by raywave** [comment]
В следующем глобальном обновлении будет исправлено.
